// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB79_cW7bIHQnXXUL0CJ_iS8zp5usE8mo8',
    appId: '1:744264233887:web:3a955cf5079fca978bc3aa',
    messagingSenderId: '744264233887',
    projectId: 'mro-damage-system',
    authDomain: 'mro-damage-system.firebaseapp.com',
    storageBucket: 'mro-damage-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInK5DeD8sD5Z4YxOg7vKhTCMzgoP5AY0',
    appId: '1:744264233887:android:1ff9e61bd4c9be448bc3aa',
    messagingSenderId: '744264233887',
    projectId: 'mro-damage-system',
    storageBucket: 'mro-damage-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9LqOqkwar_NQ251K6wd3IXxSZ9iU0Tsw',
    appId: '1:744264233887:ios:9e9f16395b8dbf5d8bc3aa',
    messagingSenderId: '744264233887',
    projectId: 'mro-damage-system',
    storageBucket: 'mro-damage-system.firebasestorage.app',
    iosBundleId: 'com.mroam.mroDamageSystem',
  );
}
